### ISSUE TITLE
Validate that documented filters and sorters are correct

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/api-schema-validator#6]
The schema validator should check that the filters and sorters present on list endpoints, like https://developer.sailpoint.com/idn/api/v3/list-sources, are accurate and work.  It should also identify any filters/sorters that are supported but aren't documented.

- Only execute on beta and v3 IDN APIs.  These versions have a standard for filters/sorters that can be validated.
- Test with real values.  The validator must fetch unfiltered results first in order to test real values against the endpoint.
- Test all [primitive operators](https://developer.sailpoint.com/idn/api/standard-collection-parameters#primitive-operators) for each top level attribute
  - Any top level attribute that is a primitive type (ex. string, number, boolean)
  - Any reference objects that have `name` and `id` as attributes.  These are more common to support filtering than regular objects.
  - Otherwise, don't test arrays or objects unless explicitly supported in the filter description
- Don't test composite operators.  These should be supported on any endpoint that has filtering, and adding these to the tests would dramatically increase the test surface.

**Comment by jordan-violet-sp** [comment]
Currently being worked on in this branch: https://github.com/sailpoint-oss/api-schema-validator/tree/features/filter-sorter-tests
